version: "3.1"

services:

  adrienh_mysql:
    image: "mysql"
    command: "--default-authentication-plugin=mysql_native_password"
    environment:
      MYSQL_USER: "adrienh"
      MYSQL_PASSWORD: "adrienh"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3300:3306"

  adrienh_adminer:
      image: "adminer"
      ports:
        - "4000:8080"